[project]
name = "MIASquare"
authors = []
description = ""
telemetry = false
requirements = []
cache_dir = "/home/boris/Projects/MiamiSquare/MIASquare/./.requirements"
boot_contracts = ["pox", "costs-v2", "bns"]

[contracts.ft-trait]
path = "contracts/sips/ft-trait.clar"
depends_on = []

[contracts.miasquare-token]
path = "contracts/miasquare-token.clar"
depends_on = ["ft-trait"]

[contracts.miasquare]
path = "contracts/miasquare.clar"
depends_on = ["miasquare-token"]

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
